# Generated by Django 4.1.4 on 2023-01-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, help_text='first Name', max_length=30, verbose_name='First Name')),
                ('lname', models.CharField(help_text='Last Name', max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(help_text='Email Address', max_length=254)),
                ('password1', models.CharField(max_length=10)),
                ('password2', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('colors', models.CharField(choices=[('', '--select--'), ('R', 'RED'), ('G', 'GREEN'), ('BL', 'BLUE'), ('B', 'BLACK'), ('W', 'WHITE')], max_length=20)),
            ],
        ),
    ]
